### ISSUE TITLE
KSframework for Unity 2017

### ISSUE THREAD

**Issue by xJayLee** [mr-kelly/KSFramework#10]
not working

**Comment by zhaoqingqing** [comment]
what is happen?  Posted on the log

**Comment by xJayLee** [comment]
很多宏定义，比如SceneLoader里 //#if UNITY_5

**Comment by zhaoqingqing** [comment]
@KrisLee  近期会对脚本中使用到的宏定义进行更新。

**Comment by zhaoqingqing** [comment]
@KrisLee 宏定义已经添加上去了，在Unity2017下测试通过，你可以获取KEngine和KSFramework尝试
