### ISSUE TITLE
 The name `SceneLoader' does not exist in the current context

### ISSUE THREAD

**Issue by LukeChenyk** [mr-kelly/KSFramework#14]
unity 2017.2.0f3 has this error:
Assets/Code/Game.cs(82,9): error CS0103: The name `SceneLoader' does not exist in the current context

**Comment by psygames** [comment]
KSFramework\Assets\Plugins\KEngine\KEngine\CoreModules\ResourceModule\SceneLoader.cs
modify line 29 #if UNITY_5 || UNITY_2017 || your UnityVersion

**Comment by zhaoqingqing** [comment]
@LukeChenyk  你需要使用KEngine仓库的代码 https://github.com/mr-kelly/KEngine/

**Comment by zhaoqingqing** [comment]
目前已经支持2017及更新的版本。
