### ISSUE TITLE
Unity2017,打成安卓包之后加载资源失败

### ISSUE THREAD

**Issue by X-MENG** [mr-kelly/KSFramework#16]
在game.unity的基础上简单改了一下，但是执行SceneLoader.Load("Scene/TestScene/TestScene.unity");的时候会看到加载失败的log类似这样：
[ERROR][HotBytesLoader]Error Load WWW: jar:file:///data/app/com.github.KSFramework-1/base.apk!/assets/Bundles/Android/scene/testscene/testscene.unity.k
[ERROR][AssetBundleLoader]Error Load Bytes AssetBundle: scene/testscene/testscene.unity.k
[ERROR][KWWWLoader:Error]404 Not Found jar:file://data/app/com.github.KSFramework-1/base.apk!/assets/Bundles/Android/scene/testscene/testscene.unity.k

打开apk包查看了一下，资源都在包里，但却报告找不到，请问这是怎么回事呢？

**Comment by zhaoqingqing** [comment]
更新KEngine后，问题已解决。
