### ISSUE TITLE
unity5.6打开工程后报错 

### ISSUE THREAD

**Issue by iiccttff** [mr-kelly/KSFramework#17]
Assets/Plugins/KSFramework/Modules/UI/LuaUIController.cs(157,38): error CS1001: Unexpected symbol `[', expecting identifier

Assets/Plugins/KSFramework/Modules/UI/LuaUIController.cs(157,54): error CS1525: Unexpected symbol `]', expecting `;' or `}'

**Comment by zhaoqingqing** [comment]
从错误来看，可能是文件编码引起的错误。
你可以用文件打开尝试对文件进行重新保存，格式为UTF-8-BOM。
如果在mac下用不同的编辑器打开，行尾可能会不一致。
