### ISSUE TITLE
MAC平台下面的使用rider+emmyLua debug的方法

### ISSUE THREAD

**Issue by afantree** [mr-kelly/KSFramework#26]
在mac上用emmylua插件进行lua debug的时候，出现了下图的错误
![image](https://user-images.githubusercontent.com/3734851/92299441-bf27ce80-ef84-11ea-9b3b-dad0316e17c2.png)

查了下xlua官方文档，说是加入-DLUA_USE_DLOPEN 重新编译即可
KSFramework使用的xlua 编译包是来自于https://github.com/chexiongsheng/build_xlua_with_libs 这个库的，所以下载下来加入参数重新编译即可

想要直接编译好的，加入KSFramework官方群，里面问问即可

**Comment by afantree** [comment]
做个笔记，谁要是遇见问题了，就拿去

**Comment by Codopia1016** [comment]
这个具体怎么操作呀
