### ISSUE TITLE
Android真机上加载Sprite失败

### ISSUE THREAD

**Issue by darius2013** [mr-kelly/KSFramework#28]
![image](https://user-images.githubusercontent.com/3467883/101483694-82101580-3993-11eb-8de8-8ee4cdf25797.png)
真机上按钮的贴图没有显示，也没有资源加载失败的日志。但是编辑器中，加载Android资源没问题
unity版本是2019.3.7f

**Comment by zhaoqingqing** [comment]
已知，Unity的SpriteAtlas问题，后续会增加ugui的图集管理。

**Comment by zhaoqingqing** [comment]
请更新，已加入对SpriteAtlas的管理，包含以下内容：
在UI编辑器中预览或从Assetbundle中加载SpriteAtlas都做了处理。
同时SpriteAtlas中的两种模式IncludeInBuild都处理了。
