### ISSUE TITLE
能不能加个从lua加载资源的例子

### ISSUE THREAD

**Issue by xiuzhifu** [mr-kelly/KSFramework#29]
我的UI有个动态切换的图，想从lua中从图集加载sprite，但是，找不到文档或者例子，只有一个c#的，api在lua中，好像不能用，能不能说明一下，谢谢

**Comment by zhaoqingqing** [comment]
@xiuzhifu 在xlua中访问c#的api，加上CS.namespace.className.方法名

**Comment by xiuzhifu** [comment]
@zhaoqingqing 你好，能不能写个示例代码，我不太知道怎么调用

**Comment by zhaoqingqing** [comment]
@xiuzhifu 例子已加上，查看这个提交：[add 在lua中动态替换图片的例子](https://github.com/mr-kelly/KSFramework/commit/4a0641326493f0d24d01294350b43dbc20f1a237)
使用方法：运行游戏，点击左上角的图标，在打开的UIRoleInfo界面中，点击中间的人物图片，观看左侧的图片就更换了。
