### ISSUE TITLE
atlas_common.spriteatlas 问题

### ISSUE THREAD

**Issue by xiuzhifu** [mr-kelly/KSFramework#30]
https://github.com/mr-kelly/KSFramework/blob/master/KSFramework/Assets/KSFramework/KEngine/KEngine/CoreModules/ResourceModule/KAssetFileLoader.cs#L215 
这行代码会导致 atlas_common.spriteatlas   m_Name字段一直增长
由atlas_common变成atlas_common (UnityEngine.SpriteAtlas)~uiatlas/atlas_common...

**Comment by zhaoqingqing** [comment]
@xiuzhifu 你好，请问你是怎么操作复现的？ 这个atlas_common设计是只加载一次且常驻内存的。

**Comment by xiuzhifu** [comment]
在unity编辑器下面多运行几次就会出现，我没找到怎么引起的，现在的办法，是运行前，执行一次，KUGUIBuilder.BuildCommonAtlas();重新导出一下公共图集，就不会有问题

**Comment by zhaoqingqing** [comment]
ok，我周末尝试复现一下

**Comment by xiuzhifu** [comment]
原因可能不是这一行，删掉了，还是会增长

**Comment by xiuzhifu** [comment]
后面确认，确实是这个原因
