### ISSUE TITLE
KSframework for Unity 5.6.1f1

### ISSUE THREAD

**Issue by itech4ever** [mr-kelly/KSFramework#9]
你好，是不是KSframework还不支持5.6.1的版本？一直报错：

Assets/SLua/LuaObject/Unity/LuaDelegate_UnityEngine_Collections_DisposeSentinel_DeallocateDelegate.cs(11,86): error CS0122: `UnityEngine.Collections.DisposeSentinel' is inaccessible due to its protection level

多谢。

**Comment by zhaoqingqing** [comment]
KS支持UNITY5.6，这个错误是unity的接口访问级别有修改，你改下出错行的代码就可，pull到这儿来。

**Comment by ZengHuiPan** [comment]
怎么修改啊 不会改啊

**Comment by zhaoqingqing** [comment]
已支持 Unity2017
